### ISSUE TITLE
ReadMe Docs import line Update

### ISSUE THREAD

**Issue by jaybharadia** [novaday-co/otp-input-vue#4]
Thank you for making this open source otp input package. It is really great. 
One minor feedback for documentation is that 
- Import line is actually not correct. I have attached screenshots.

Incorrect 
![image](https://user-images.githubusercontent.com/28944638/198835956-7a628d96-6cca-4089-898c-d9cad662da1d.png)

Correct Version
![image](https://user-images.githubusercontent.com/28944638/198836019-61b8065b-0363-4b1b-9e73-6dce36de635d.png)

**Comment by jaybharadia** [comment]
Please check this PR #5

**Comment by shahriarEshraghi** [comment]
Hi @jaybharadia Thank you for your contribution.
